### ISSUE TITLE
quoteStyle should be by default double

### ISSUE THREAD

**Issue by GrimLink** [Jakobud/vscode-placeholder-images#1]
Why is the quote style single by default?

It makes more sense to have this to the HTML standard quote style.

**Comment by Jakobud** [comment]
Thanks for the feedback. I'm curious what HTML standard are you referring to?

w3 makes it pretty clear that there is no difference or advantages between using them and that it really just comes down to personal style. https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2

If anything, the one advantage of a single quote is that it's less keystrokes when typing (since you have to hold down Shift to get a double quote). That's pretty much why I stick with single quotes personally.

I'm not likely to change this simply because anyone who uses the extension has the choice to change the value in their settings.

**Comment by GrimLink** [comment]
Wel I am not referring to a specific standard.
More to a general standard.

- All examples use double, e.g. developer.mozilla.org
- All styles guide point to the use of double (have not found one with single)
  - https://google.github.io/styleguide/htmlcssguide.html#HTML_Quotation_Marks
  - http://codeguide.co/#html-syntax
- Some JS languages requires this.
- All browser render it as double.

And while true that html does not really care if it is double or single.
_Why the html4 docs btw?_
Similar to some HTML that don't need to be closed, e.g. `<li>`
It makes more sense to stick to a general standard that is used by many devs.

**Comment by Jakobud** [comment]
You make some good points. I'll consider making the change on my next release.
